/* Women in STEM — site data (edit content here)
 *
 * Content workflow:
 * - Add events to events.upcoming / events.past (see field structure on each event object)
 * - Add blogPosts and podcastEpisodes (omit entries without a title from public arrays)
 * - Internal planning items go in contentPlanning — not rendered on the site
 * - Set directorApplication.url when the application form is available
 * - Set links.social[].url when verified social/content URLs are available
 */

const WIS_DATA = {
  site: {
    name: "Women in STEM",
    university: "Western University",
    location: "Western University · London, Ontario",
    disclaimer: "A student-run club, not officially affiliated with the University Students' Council.",
    /* Used in footer — matches existing approved homepage messaging */
    missionStatement: "Empowering women and gender-diverse students in STEM through community, mentorship, research exposure, and connection.",
    westernUrl: "https://www.uwo.ca",
  },

  links: {
    membership: {
      url: "https://westernusc.store/product/western-women-in-stem/",
    },
    email: "womeninstemuwo@gmail.com",
    logo: "images/logo/classic_logo.jpg",
    social: [
      { label: "Instagram", url: "https://www.instagram.com/womeninstemuwo?igsh=MWI1dnM4aWpiNDBseQ==" },
      { label: "TikTok", url: "https://www.tiktok.com/@womeninstemuwo?_r=1&_t=ZS-98oM8sHvwZg" },
      { label: "Linktree", url: "https://linktr.ee/womeninstemuwo?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAdGRleAToyLpwZG9mAmZkaWQWUMUscpHmFch5y12ZM6RQW25-I5qaSWV4dG4DYWVtAjExAHNydGMGYXBwX2lkDzEyNDAyNDU3NDI4NzQxNAABp9j5Xw4RovcgEstEcTXzqZd5N5Ly6oultEcqfYOuXoVR-c0yu4q6f2jX3QbQ_aem_pirGOI3-ybRkwZPzigy04g" },
      { label: "Blog", url: "https://wisblog.wixsite.com/womeninstemuwo" },
      { label: "Podcast", url: "https://open.spotify.com/show/0KyHgRbSzHDQeWoWzHN5fI?si=KnLN4_msQte2SLHCv2bA-g&utm_source=sms" },
    ],
  },

  mentorship: {
    url: "https://docs.google.com/forms/d/e/1FAIpQLScEUi4kfFoiUUmBSPtUvmcg0exMSexp1zuS9Ft47A7keJXpZw/viewform?usp=header",
    title: "Become a Little Sister",
  },

  directorApplication: {
    url: "https://docs.google.com/forms/d/e/1FAIpQLSeZuE0pdRPMU0vu2OnhMFOWYcuFI-rymMQ1Q13A90cUiLbZKw/viewform?usp=header",
    status: "open",
    title: "Director Applications",
    timing: "Applications open in September",
  },

  stats: [
    { num: "250+", label: "Members across faculties" },
    { num: "15+", label: "Events run each year" },
    { num: "40", label: "Mentorship pairs this term" },
    { num: "12", label: "Partner labs & companies" },
  ],

  hero: {
    headline: "Your community in STEM starts here.",
    lede: [
      "Women in STEM at Western is a student-run community focused on empowering women in STEM while welcoming students from across all STEM programs. We're dedicated to helping people feel confident, connected, and supported throughout their time at Western.",
      "We bring students together with mentors, researchers, professionals, and, most importantly, each other.",
      "Whether you're looking to learn more about different opportunities, explore different paths in STEM, or simply meet new people, there's a place for you at WIS!",
    ],
  },

  mission: {
    eyebrow: "At WIS",
    title: "What can you find at WIS?",
    description: [
      "WIS offers everything from mentorship and career development to workshops, helpful resources, and social events throughout the year.",
      "From the Toronto Trip and WeSolve Case Competition to Coffee & Croissants, Suture Clinic, Puppy Yoga, and our Big Sister Little Sister Mentorship Program, there's always something happening at WIS and plenty of ways to get involved, learn something new, and make meaningful connections.",
    ],
  },

  home: {
    closing: {
      title: "Finding your way in STEM is easier with the right people around you",
      description: "Whether you're thinking about courses, research, careers, or what comes next, WIS gives you a space to ask questions, learn from others, and navigate your time at Western with more confidence.",
    },
  },

  pillars: [
    {
      label: "01 - MENTORSHIP",
      title: "Mentorship",
      description: "Learn from students who have been where you are. Our mentorship programs connect you with upper-year students who can share advice, answer questions, and help you navigate your STEM journey at Western.",
    },
    {
      label: "02 - COMMUNITY",
      title: "Community",
      description: "Find your people in STEM. Through social events, study sessions, and opportunities to meet students across different programs, WIS makes it easier to build connections and feel at home in your community.",
    },
    {
      label: "03 - RESEARCH & CAREERS",
      title: "Research & Careers",
      description: "Explore where a STEM degree can take you. Connect with researchers, industry professionals, and fellow students to discover research, career, and professional opportunities beyond the classroom.",
    },
  ],

  events: {
    upcoming: [
      {
        title: "Development + CI Study Sessions",
        category: "Academic",
        date: "Ongoing biweekly beginning September 17, 2026",
        dateShort: "SEP 17+",
        time: "12:00–2:00 PM",
        location: "Taylor or Weldon study room — exact room TBD",
        description: "Biweekly study sessions providing members with a dedicated space to work on coursework, collaborate with peers, and build connections within the WIS community. Some sessions may feature themes such as MCAT preparation.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: null,
      },
      {
        title: "BSLS — Little Applications Open",
        category: "Mentorship",
        date: "September 21–27, 2026",
        dateShort: "SEP 21–27",
        time: null,
        location: "Online",
        description: "Forms go online for Littles to apply for the mentorship program.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: "Pairings are expected to be released by email October 5, 2026.",
      },
      {
        title: "Cookie Fundraiser",
        category: "Fundraiser",
        date: "October 5–9, 2026 (tentative)",
        dateShort: "OCT 5–9",
        time: null,
        location: "Campus booths, including Ivey, Natural Science, UCC, and Weldon areas",
        description: "A campus-wide cookie fundraiser featuring a variety of flavours. Proceeds support WIS programming and help introduce more students to the club.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Bracelet Making Social",
        category: "Social",
        date: "October 7, 2026",
        dateShort: "OCT 7",
        time: null,
        location: "Weldon Community Room or UCC Community Room — exact location TBD",
        description: "Members can choose charms and make bracelets for themselves while connecting with the WIS community.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: "$5 for non-members.",
      },
      {
        title: "Suture Clinic",
        category: "Professional Development / Healthcare",
        date: "October 7, 2026",
        dateShort: "OCT 7",
        time: "6:00 PM",
        location: "UC Room — exact room TBD",
        description: "A hands-on workshop where participants learn and practice basic suturing techniques under the guidance of trained instructors. The session introduces foundational clinical skills and provides an opportunity to explore healthcare careers.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: "Potential collaboration with Pre-Med society / Medical School Fair — not confirmed.",
      },
      {
        title: "Classroom Visits — Toronto Trip Promotion",
        category: "Professional Development",
        date: "October 26–30, 2026",
        dateShort: "OCT 26–30",
        time: null,
        location: "Western University classrooms / STEM lecture halls",
        description: "WIS Events VPs and Directors will visit STEM lecture halls to introduce students to the Toronto Trip, explain the trip and its benefits, and encourage students to sign up.",
        purpose: null,
        registrationUrl: null,
        status: "Exact classroom schedule TBD",
        notes: null,
      },
      {
        title: "Painting Iced Coffee Cups Social",
        category: "Social",
        date: "First week of November 2026 (tentative)",
        dateShort: "EARLY NOV",
        time: null,
        location: "UC room",
        description: "A creative BSLS-only social after Big Sister Little Sister pairings are announced. Members can decorate and personalize iced coffee cups while connecting with their Bigs and Littles.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Speed Coffee Chatting — Group 1",
        category: "Professional Development / Networking",
        date: "Wednesday, November 4, 2026",
        dateShort: "NOV 4",
        time: "5:00 PM",
        location: "UC room",
        description: "A networking event where members rotate through short, timed conversations with upper-year students, alumni, or graduate students. Ask questions about academics, research, career paths, internships, and professional school in a relaxed setting.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: null,
      },
      {
        title: "Connect to Success",
        category: "Professional Development",
        date: "Mid-November 2026 (tentative)",
        dateShort: "MID NOV",
        time: null,
        location: "Mustang Lounge",
        description: "A professional development workshop to help members prepare for the Toronto Trip by strengthening resume, LinkedIn, networking, and professional communication skills. Includes interactive presentations, networking tips, and time to connect with other trip attendees.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date — timing depends on the Toronto Trip",
        notes: null,
      },
      {
        title: "Pre-Toronto Trip Socials",
        category: "Social",
        date: "November 15–21 or November 22–27, 2026 (tentative)",
        dateShort: "MID–LATE NOV",
        time: null,
        location: "Determined by each group",
        description: "Toronto Trip groups will meet for a pre-trip social with their group members and WIS executive group lead. Each group can choose an activity such as a board game night, dinner, paint night, or virtual social.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Toronto Trip",
        category: "Professional Development / Networking",
        date: "November 2026 — date to be announced",
        dateShort: "NOV TBA",
        time: null,
        location: "Toronto, Ontario, including locations surrounding the MaRS Discovery District",
        description: "A full-day experience where approximately 100 selected WIS members from various STEM programs travel to Toronto to visit firms, laboratories, hospitals, and research facilities. Students can network with professionals, connect with other STEM students, and explore diverse STEM careers.",
        purpose: "Career exploration, professional development, networking, and exposure to diverse STEM career paths.",
        registrationUrl: null,
        status: "Date TBA — potential dates November 20 or November 27, 2026",
        notes: null,
      },
      {
        title: "Puppy Yoga",
        category: "Wellness / Social",
        date: "November 19, 2026",
        dateShort: "NOV 19",
        time: null,
        location: "UCC Community Room",
        description: "A wellness event featuring puppy yoga sessions designed to give members a fun opportunity to relax and recharge during the academic term.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: null,
      },
      {
        title: "Wellness Packages — Fall",
        category: "Wellness",
        date: "End of November 2026 (tentative)",
        dateShort: "LATE NOV",
        time: null,
        location: "Taylor Library boothing table",
        description: "Wellness packages will be distributed to members during exam season as a small reminder to prioritize wellbeing during a stressful time of year.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Coffee & Croissants",
        category: "Professional Development / Networking",
        date: "Late November–early December 2026 — exact date TBD",
        dateShort: "LATE NOV",
        time: null,
        location: "Mustang Lounge or another Western University location — TBD",
        description: "A career-focused networking event where members can ask WIS executives and experienced students about internships, research, networking, interviews, coffee chats, career paths, and university experiences.",
        purpose: "Research & Internship Opportunities / Student Experiences",
        registrationUrl: null,
        status: "Date TBD",
        notes: null,
      },
      {
        title: "Coco & Cram",
        category: "Academic / Social",
        date: "December 1, 2026 (tentative)",
        dateShort: "DEC 1",
        time: null,
        location: "UC classroom",
        description: "A cozy December study social where WIS members can study, connect with senior executives and other members, and enjoy a festive atmosphere with hot chocolate or other refreshments.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Trivia Night",
        category: "Social",
        date: "Second week of classes in January 2027 (tentative)",
        dateShort: "JAN 2027",
        time: null,
        location: "The Spoke",
        description: "A themed trivia night hosted in partnership with The Spoke, giving WIS members a chance to relax, meet others, and enjoy a social evening together.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "New Year Vision Board",
        category: "Wellness / Social",
        date: "Thursday, January 14, 2027",
        dateShort: "JAN 14",
        time: "6:00 PM",
        location: "UCC or UC classroom",
        description: "A creative workshop where participants design personalized vision boards reflecting academic, personal, and professional goals for the upcoming year or semester. Use craft supplies, photos, quotes, and other materials while connecting with peers in a relaxed environment.",
        purpose: null,
        registrationUrl: null,
        status: null,
        notes: null,
      },
      {
        title: "BSLS Board Game Café Social",
        category: "Social",
        date: "Thursday before Reading Week 2027 (tentative)",
        dateShort: "FEB 2027",
        time: null,
        location: "Saga Board Games & Coffee, downtown London",
        description: "A BSLS-only social at Saga Board Games & Coffee where Bigs and Littles can spend time together in a relaxed and engaging environment.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "How to Case Comp Workshop",
        category: "Professional Development",
        date: "Approximately one week before the case competition — exact date TBD",
        dateShort: "FEB/MAR TBA",
        time: null,
        location: "Small lecture room or Zoom — TBD",
        description: "A workshop introducing participants to case competition fundamentals, how to approach a case, and what to expect during the competition.",
        purpose: null,
        registrationUrl: null,
        status: "Potential dates: February 28 or March 7, 2027",
        notes: null,
      },
      {
        title: "Coffee & Croissants — Semester 2",
        category: "Professional Development",
        date: "February/March 2027 — exact date TBD",
        dateShort: "FEB/MAR 2027",
        time: null,
        location: "Western University room — TBD",
        description: "A semester-two Coffee & Croissants event focused on ITR-related questions, student experiences, and career/academic conversations with WIS executives.",
        purpose: null,
        registrationUrl: null,
        status: "Date TBD",
        notes: null,
      },
      {
        title: "24-Hour WeSolve Case Competition",
        category: "Professional Development / Competition",
        date: "March 2027 — exact date TBD",
        dateShort: "MAR 2027",
        time: null,
        location: "Western University — exact rooms TBD",
        description: "A beginner-level case competition where WIS members work in teams to develop a solution to a case and present it to a panel of judges. The experience will also include speakers and workshops focused on networking, case competition skills, and LinkedIn development.",
        purpose: null,
        registrationUrl: null,
        status: "Potential dates: March 6–7 or March 13–14, 2027",
        notes: null,
      },
      {
        title: "Career Networking Hour — Group 2",
        category: "Professional Development / Networking",
        date: "March 2027, during Women’s Week (tentative)",
        dateShort: "MAR 2027",
        time: null,
        location: "UC room",
        description: "A networking event where members can connect with WIS executives, upper-year students, alumni, and professionals to learn about co-op experiences, internships, research opportunities, and different career pathways in STEM. Includes small-group discussions and an informal Q&A.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Bouquet Making Fundraiser",
        category: "Fundraiser",
        date: "March 6–9, 2027 (tentative)",
        dateShort: "MAR 6–9",
        time: null,
        location: "Accessible campus booth",
        description: "A campus bouquet-making fundraiser where students can create bouquets for themselves or someone they love. Different bouquet sizes and individual flowers will be available, with guidance on how to assemble them.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date — around International Women’s Day/Week",
        notes: null,
      },
      {
        title: "International Women’s Week Bouquet Making",
        category: "Social",
        date: "During International Women’s Week 2027 (tentative)",
        dateShort: "IWW 2027",
        time: null,
        location: "UCC Atrium booth",
        description: "Celebrate International Women’s Week by creating your own bouquet. Participants can choose flowers and create a personalized bouquet, with paper and a small card provided.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
      {
        title: "Women’s Fitness Run",
        category: "Wellness / Social",
        date: "End of March 2027 (tentative)",
        dateShort: "LATE MAR",
        time: null,
        location: "Outdoor route beginning near campus",
        description: "A 5K community run beginning near campus that promotes fitness, wellness, and connection among WIS members. The event may also be used as a fundraiser.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date — may align with International Women’s Week initiatives",
        notes: null,
      },
      {
        title: "Wellness Packages — Spring",
        category: "Wellness",
        date: "Beginning of April 2027 (tentative)",
        dateShort: "EARLY APR",
        time: null,
        location: "Taylor Library boothing tables",
        description: "A second wellness package distribution to support members during the exam period and encourage students to prioritize their wellbeing during a stressful time.",
        purpose: null,
        registrationUrl: null,
        status: "Tentative date",
        notes: null,
      },
    ],
    past: [],
  },

  /* Add verified resources here when available */
  resources: {
    academic: [],
    career: [],
    stem: [],
    wellbeing: [],
  },

  resourceCategories: [
    { key: "academic", label: "Academic", blurb: "Study resources, course support, and academic tools for STEM students." },
    { key: "career", label: "Career", blurb: "Resume, interview, networking, and career development resources." },
    { key: "stem", label: "STEM", blurb: "Research organizations, professional groups, conferences, and funding information." },
    { key: "wellbeing", label: "Community & Well-being", blurb: "Campus support, mentorship, and student well-being resources." },
  ],

  values: [
    {
      title: "Community",
      description: "We believe STEM is better together. WIS creates a welcoming space where students can build genuine connections, find their people, and feel like they belong.",
    },
    {
      title: "Empowerment",
      description: "We want students to feel confident in their abilities and their potential. We encourage our members to take opportunities, ask questions, and pursue the paths that are right for them.",
    },
    {
      title: "Inclusion",
      description: "Everyone deserves a place in STEM. We strive to create an environment where students from all backgrounds, programs, and experiences feel welcomed, respected, and valued.",
    },
    {
      title: "Curiosity",
      description: "There's always more to discover. We encourage students to ask questions, explore new areas of STEM, and stay curious about the possibilities beyond the classroom.",
    },
    {
      title: "Collaboration",
      description: "The best ideas grow when we learn from one another. We bring students, mentors, researchers, and professionals together to share knowledge, perspectives, and experiences.",
    },
    {
      title: "Growth",
      description: "Your STEM journey doesn't have to look one way. WIS supports students as they learn, develop new skills, explore their interests, and grow both personally and professionally.",
    },
  ],

  about: {
    whoWeAre: "Women in STEM at Western is a student-run community dedicated to empowering women and welcoming students from across all STEM programs. We create opportunities to connect, explore, and grow through mentorship, research, career development, and community.",
  },

  /* Blog posts — add listeningUrl when published externally */
  blogPosts: [
    {
      title: "Scholarships",
      author: "Finance",
      date: "September 18, 2026",
      category: "Financial Resources",
      description: "A guide to scholarship opportunities and resources for students.",
      status: "Planned",
    },
    {
      title: "Ways to Stay Active During the School Year",
      author: "Operations",
      date: "September 22, 2026",
      category: "Student Life / Wellness",
      description: "A guide to staying active during a busy school year, including Western resources, gym and intramural opportunities, and outdoor activities.",
      status: "Planned",
    },
    {
      title: "I Want to Switch Programs",
      author: "Operations",
      date: "October 20, 2026",
      category: "Academic / Student Support",
      description: "A guide for students considering changing programs, including questions to consider and where to seek guidance.",
      status: "Planned",
    },
    {
      title: "Standardized Testing Series",
      author: "Development",
      date: "November 3, 2026",
      category: "Academic / Career",
      description: "A planned content series related to standardized testing.",
      status: "Planned",
    },
    {
      title: "Investments",
      author: "Finance",
      date: "November 10, 2026",
      category: "Financial Resources",
      description: "An educational introduction to investing.",
      status: "Planned",
    },
    {
      title: "Volunteer Opportunities in London",
      author: "Operations",
      date: "November 17, 2026",
      category: "Opportunities",
      description: "A guide to volunteer opportunities in London and how students can find and apply for opportunities.",
      status: "Planned",
    },
  ],

  /* Public podcast episodes only — omit entries without a title/topic */
  podcastEpisodes: [
    {
      title: "The Art of Teaching with Dr. Derek McLachlin",
      host: "Audrey",
      date: "September 29, 2026",
      category: "Career / Academia",
      description: "An exploration of Dr. Derek McLachlin's journey from research scientist to educator, how his biochemical research background shaped his teaching approach, and his interest in the scholarship of teaching and learning.",
      status: "Recorded",
      listeningUrl: null,
    },
    {
      title: "Sophing...",
      host: "Julia",
      date: "October 27, 2026",
      category: "Student Life / Leadership",
      description: "An episode exploring the experience of being a Soph, how students can apply, and why the role can be an impactful way to get involved on campus.",
      status: "Planned",
      listeningUrl: null,
    },
    {
      title: "Standardized Testing Series",
      host: "Development",
      date: "November 3, 2026",
      category: "Academic / Career",
      description: "Planned podcast content related to standardized testing.",
      status: "Planned",
      listeningUrl: null,
    },
    {
      title: "Internships & Career Opportunities",
      host: "Finance",
      date: "October 13, 2026",
      category: "Career / Internships",
      description: "An exploration of internship and career opportunity pathways for STEM students.",
      status: "Planned",
      listeningUrl: null,
    },
  ],

  spotlights: [],

  /* Internal content planning — not rendered on public pages */
  contentPlanning: {
    podcast: [
      {
        releaseDate: "November 24, 2026",
        status: "Planned",
        topic: null,
      },
    ],
  },

  applications: [
    {
      department: "Marketing",
      title: "Director of Marketing",
      description: "Lead campaigns, social media, and brand outreach for the club.",
    },
    {
      department: "Operations",
      title: "Director of Operations",
      description: "Help run day-to-day club logistics, planning, and internal coordination.",
    },
    {
      department: "Finance",
      title: "Director of Finance",
      description: "Manage budgets, funding requests, and financial reporting for the team.",
    },
  ],

  /* Homepage team preview — first N members shown on index.html (full roster stays in team[]) */
  teamPreviewCount: 5,


  team: [
    {
      group: "Leadership",
      members: [
        { name: "Kathryn Medeiros", role: "Co-President", initials: "K.M.", image: "headshots/cropped_headshots/Kathryn_Medeiros.jpg" },
        { name: "Stephanie Vieriu", role: "Co-President", initials: "S.V.", image: "headshots/cropped_headshots/Stephanie_Vieriu.jpg" },
        { name: "Christa Cupid", role: "Senior Advisor", initials: "C.C.", image: "headshots/cropped_headshots/Christa_Cupid.jpg" },
      ],
    },
    {
      group: "Events",
      members: [
        { name: "Haley Lam", role: "VP of Events", initials: "H.L.", image: "headshots/cropped_headshots/Haley_Lam.jpg" },
        { name: "Thea Farruggio", role: "Co-VP of Events", initials: "T.F.", image: "headshots/cropped_headshots/Thea_Farruggio.jpg" },
      ],
    },
    {
      group: "Finance",
      members: [
        { name: "Sia Andros", role: "Co-VP Finance", initials: "S.A.", image: "headshots/cropped_headshots/Sia_Andros.jpg" },
        { name: "Elle Coene", role: "Co-VP Finance", initials: "E.C.", image: "headshots/cropped_headshots/Elle_Coene.jpg" },
      ],
    },
    {
      group: "Operations",
      members: [
        { name: "Audrey Tsang", role: "Co-VP of Operations", initials: "A.T.", image: "headshots/cropped_headshots/Audrey_Tsang.jpg" },
        { name: "Julia Wills", role: "Co-VP of Operations", initials: "J.W.", image: "headshots/cropped_headshots/Julia_Wills.jpg" },
      ],
    },
    {
      group: "Marketing",
      members: [
        { name: "Emily Kenoski", role: "Co-VP Marketing", initials: "E.K.", image: "headshots/cropped_headshots/Emily_Kenoski.jpg" },
        { name: "Lucy Pavlovic", role: "Co-VP Marketing", initials: "L.P.", image: "headshots/cropped_headshots/Lucy_Pavlovic.jpg" },
      ],
    },
    {
      group: "Development",
      members: [
        { name: "Madison Ruddy", role: "Co-VP Development", initials: "M.R.", image: "headshots/cropped_headshots/madison_ruddy.jpg" },
        { name: "Hailey Liu", role: "Co-VP of Developments", initials: "H.L.", image: "headshots/cropped_headshots/Hailey_Liu.jpg" },
      ],
    },
    {
      group: "Community Inclusion",
      members: [
        { name: "Ashley Oswald", role: "VP Community Inclusion", initials: "A.O.", image: "headshots/cropped_headshots/Ashley_Oswald.jpg" },
        { name: "Mufliha Fatimah Said", role: "VP Community Inclusion", initials: "M.S.", image: "headshots/cropped_headshots/Mufliha_Fatimah_Said.jpg" },
      ],
    },
  ],
};
